-- 기존 데이터 삭제
DELETE FROM POST_COMMENT WHERE 1=1;
DELETE FROM POST WHERE 1=1;
DELETE FROM MEMBER WHERE 1=1;
COMMIT;

-- 회원 데이터 생성
-- 주의: PASSWORD는 실제 BCrypt 암호화된 값으로 변경 필요
INSERT INTO MEMBER (EMAIL, PASSWORD, NICKNAME, CREATED_AT)
VALUES ('user1@test.com', '$2a$12$zdZzQ76fW7sEK7xoVAkt6uhDuA1umIBxFL/Re2obKgX2Bl/9dp4Pu', '진지향', SYSDATE);

INSERT INTO MEMBER (EMAIL, PASSWORD, NICKNAME, CREATED_AT)
VALUES ('user2@test.com', '$2a$12$ILqJjPtLtNpSGoa8Wfu09OEZEuRUT3KYQ2/8k3XLoPy05yZ8pKthi', '한라봉', SYSDATE);

INSERT INTO MEMBER (EMAIL, PASSWORD, NICKNAME, CREATED_AT)
VALUES ('user3@test.com', '$2a$12$ZTYzuYtRrpsEtrmjx/TWSuy0cWeHxtlDC41P7K1ybbJCYZx5l5Iqe', '윈터프린스', SYSDATE);

COMMIT;

-- 게시글 데이터 생성 
INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (1, '버거킹 와퍼', '버거킹 와퍼는 여전히 맛있습니다.', NULL, 0, SYSDATE - 14, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (1, 'KFC 크리스피 치킨', '바삭함이 매우 좋습니다.', NULL, 0, SYSDATE - 13, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (2, '롯데리아 새우버거', '새우버거 패티가 부드러워요.', NULL, 0, SYSDATE - 12, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (2, '서브웨이 샌드위치 추천', '샌드위치 조합 꿀팁을 공유합니다.', NULL, 0, SYSDATE - 11, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (3, '도미노피자 페퍼로니', '도미노 페퍼로니는 담백합니다.', NULL, 0, SYSDATE - 10, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (3, '피자헛 쉬림프 피자', '쉬림프가 통통하고 맛있어요.', NULL, 0, SYSDATE - 9, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (1, '파파이스 치킨', '치킨이 바삭하고 촉촉합니다.', NULL, 0, SYSDATE - 8, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (2, '스타벅스 겨울 음료', '토피넛 라떼가 가장 맛있어요.', NULL, 0, SYSDATE - 7, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (2, '투썸 케이크', '케이크가 부드럽고 달달합니다.', NULL, 0, SYSDATE - 6, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (3, '이디야 아메리카노', '깔끔한 산미가 좋아요.', NULL, 0, SYSDATE - 5, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (1, '메가커피', '여기서는 커피를 먹는게 아닙니다.', NULL, 0, SYSDATE - 4, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (2, '컴포즈커피 라떼', '부드럽고 고소한 맛입니다.', NULL, 0, SYSDATE - 3, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (3, '할리스 바닐라 라떼', '달달한 바닐라 향이 좋아요.', NULL, 0, SYSDATE - 2, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (1, '폴바셋 라떼', '진하고 고소한 풍미가 있습니다.', NULL, 0, SYSDATE - 1, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (2, '노옥다', '모든 메뉴가 맛있습니다. 추천해요~', NULL, 0, SYSDATE - 15, NULL);

INSERT INTO POST (MEMBER_ID, TITLE, CONTENT, IMAGE_URL, READ_COUNT, CREATED_AT, UPDATED_AT)
VALUES (3, '모현각', '아무것도 먹지 않는게 최고의 선택입니다.', NULL, 0, SYSDATE, NULL);

COMMIT;